### PR TITLE
Most project compile on OS X

### PR DESCRIPTION
**Pull request by haf**
I had to go through and manually replace all `\` to `/`. That was time consuming, but easy.

I replaced all the nuget stuff with Paket to get control of the packages. There was an out-of-date package, MathNet, that used both 3.5 and 3.6 and both the unsigned and the signed nuget. I fixed that to use the later and signed one. Since then it seems 3.7 is out though, and `paket update` should be run.

Some lingering errors:
- chapter 1 - Visualizer uses Windows Forms, this probably can only be fixed by replacing Windows Forms with something else.
- chapter 3 - The type provider does not agree with the schema
- chapter 4 - FSharp.Charting is not cross platform, see
  https://github.com/fslaborg/FSharp.Charting/issues/29\#issuecomment-55056158
- chapter 8 - dependency on a binary Windows-based nuget, added linux
  nuget, haven't tested yet

The link for FSharp.Charting leads to a rabbit hole that ends up with [XPlot](https://github.com/TahaHachana/XPlot) that plots in the browser; however, since @tpetricek wrote in that thread it seems they've made some, but not all, progress to make Gtk bindings work on OS X. However, this code-base still needs to pull in that nuget for it to work, and that hasn't been done in this PR.

For the KML reference, [these are the docs](http://numerics.mathdotnet.com/MKL.html) and they provide good guidance on how to make it work cross platform. I added the linux package for x64; this will require you to use homebrew on OS X to install the x64 version of mono `brew install mono`.

### CODE REVIEW

**Comment by mathias-brandewinder** [comment]
Dude - thanks a ton for this, it's awesome. I need to take a detailed look first, but expect to merge that in the next couple of days. Thank you!

**Comment by haf** [comment]
Ping?

**Comment by mathias-brandewinder** [comment]
Hey Henrik,
Sincere apologies for the delayed reaction. Your PR triggered a longer-than-expected train of thoughts, specifically around Paket. In the book, after some debate, I decided to stick with straight nuget, even though I am a Paket fan. Now this re-opened that question, with a secondary one: how should I handle the fact that the repo will diverge from the code in print?
Anyways, merging in - I think the move to Paket is right, especially in the context of scripts; and diverging from the original is the point of having this repo, to fix and improve, so I just tagged the original version.
Big thanks! And sorry again for being slow.

**Comment by haf** [comment]
@mathias-brandewinder Thanks for merging; looking forward to when this all runs on mono off the shelf :) – I'm going to go through this at some point and fix it all.

**Pull request merged**
